### PR TITLE
Sync with AnacondaRecipes

### PR DESCRIPTION
**Pull request by jjhelmus**
Sync with the recipe in the AnacondaRecipes repository

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks!

**Comment by jasongrout** [comment]
The build number should have been bumped here, right?

**Comment by jjhelmus** [comment]
The contents of the file will be the same so there is no need for a build number bump.

**Comment by jasongrout** [comment]
> The contents of the file will be the same so there is no need for a build number bump.

Since the meta.yaml is stored in the built package file, the contents of the built package `.tar.gz` file *are* changing, right?

**Comment by jjhelmus** [comment]
> Since the meta.yaml is stored in the built package file, the contents of the built package .tar.gz file are changing, right?

The contents of the .tar.bz2 will be difference as the recipe is stored in the tarball.  The Python portions should be the same. Bumping the build number is never a bad idea.

**Comment by jasongrout** [comment]
> Bumping the build number is never a bad idea.

+1 (aside from "never say never" :).

**Comment by jasongrout** [comment]
I'm a little surprised if there isn't a failure if conda-forge tries to upload a package file that already exists. I (naively?) imagined that each conda-forge build that succeeded and was uploaded was essentially immutable on the server. 

Or was there a failure?

**Comment by jjhelmus** [comment]
There is logic in the [upload_or_check_non_existance](https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/upload_or_check_non_existence.py) script that checks to see if a package of the same name already exists on the conda-forge channel.  When it does no upload is performed.  This is indicated by the following in the log:

```
Distribution /home/conda/feedstock_root/build_artifacts/noarch/ipywidgets-7.3.1-py_0.tar.bz2 already 
exists for conda-forge.
```

**Comment by jasongrout** [comment]
Thanks for looking into this. Wow, silently failing to upload - I wonder if there is a way to throw a much bigger error.

**Comment by jjhelmus** [comment]
AFAIK this is not a silent error, it is intended behavior.  There are various reason why a feedstock might be modified in a way in which no new artifact is generated; token updates, README layout, adding maintainers.  In all of these cases the CI will run but there is no need to upload the build artifact.  If you are concerned I'd raise an issue in the [conda-forge./conda-forge-build-setup-feedstock](https://github.com/conda-forge/conda-forge-build-setup-feedstock]) repo.

**Comment by jasongrout** [comment]
> In all of these cases the CI will run but there is no need to upload the build artifact.

Very good point. It makes sense that the way to explicitly trigger a build is to actually change the version number or build number (i.e., something that will affect the filename of the built package).

Note to self, then: the master branch may not reflect the currently uploaded package.

**Pull request merged**
