### PR TITLE
Tighter version requirement on widgetsnbextension

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
cf https://github.com/jupyter-widgets/ipywidgets/issues/1678.

@jasongrout, I am unsure if the conda dependency solver will resolve to an earlier build number when forcibly trying to get a too recent nbextension (e.g. 4.0 when it is out).

Another PR coming for the 6.0 release.

**Comment by SylvainCorlay** [comment]
@mwcraig  : we have a branch for the 5.x series and will probably need a branch for the 6.x series. Should I branch out from the 6.0.0 release commit? Is there anything that we need to do w.r.t. to the token issue if I branch out from an old commit dating from before we re-added the repo.

**Comment by jakirkham** [comment]
Are you planning to do more 6.x releases? If so, yes. If not, no. Though this decision can always be delayed until there is a need for another 6.x release.

**Comment by SylvainCorlay** [comment]
We have made extra 5.x releases in the past.
6.x releases may occur for security reason I guess.

**Comment by jakirkham** [comment]
IMHO would create the 6.x branch when there is need to. IOW when either 6.0.1 or 6.1.0 is cut.

**Comment by jasongrout** [comment]
I hope to release a 6.0.1 soon, with a few bugfixes. But regardless, we need to release a new build of 6.0 with the updated dependency.

+1 to this change that preemptively fixes the potential problem for the next release.

**Comment by jakirkham** [comment]
Ok, there is now a `6.x` branch on the last commit that still had version 6.

**Comment by jasongrout** [comment]
> Ok, there is now a 6.x branch on the last commit that still had version 6.

Thanks!

**Comment by SylvainCorlay** [comment]
I opened another PR to the 6.x branch and added a commit to this one requiring traitlets<5.0.0.

**Comment by jakirkham** [comment]
Out of curiosity, is this constraint still relevant for recent releases of `ipywidgets`?

**Comment by jasongrout** [comment]
ipywidgets still has a tight restriction on widgetsnbextension versions in source: https://github.com/jupyter-widgets/ipywidgets/blob/adfb196507069aca34705bf35ec3a3f9c6724957/setup.py#L122

The `traitlets<5` constraint is just future-proofing us against future possibly breaking changes in traitlets.

**Pull request merged**
