### PR TITLE
Add jason to ipywidgets feedstock

### PR DESCRIPTION
**Pull request by SylvainCorlay**
@jasongrout

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
I am seeing such failures on `ipywidgets-feedstock` and `widgetsnbextension-feedstock` while only adding a recipe maintainer.

**Comment by SylvainCorlay** [comment]
Just rerendered the feedstock. We will see if it fixes the issue.

**Comment by jakirkham** [comment]
Could you please break out the re-rendering change from the recipe changes?

**Comment by jakirkham** [comment]
Also `conda smithy rerender --commit` will allow you to review and commit with the default message.

**Comment by SylvainCorlay** [comment]
> Could you please break out the re-rendering change from the recipe changes?

I can do that but the CI queues are already pretty long and I would rather keep my spot in the line :)

The only change in the recipe is add @jasongrout in the recipe maintainers list.

**Comment by SylvainCorlay** [comment]
After a few hours the travis CI build finally started.

Failing with the same message as earlier.

```
  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
  curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
  bash $MINICONDA_FILE -b
  
  export PATH=/Users/travis/miniconda3/bin:$PATH
  conda config --add channels conda-forge
  conda config --set show_channel_urls true
  conda install --yes --quiet conda-forge-build-setup
  source run_conda_forge_build_setup
  " failed and exited with 1 during .
```

**Comment by SylvainCorlay** [comment]
Cancelling the rest of the build to reduce the queue.

**Comment by jakirkham** [comment]
The version of `conda-smithy` is too old. Please update. Should be like `1.4.6`.

**Comment by SylvainCorlay** [comment]
Superseded by #15 .

**Pull request closed without merging**
