### PR TITLE
Remove Python 3.10 upper bound

### PR DESCRIPTION
**Pull request by jtpio**
Opening this as a draft PR to see if conda is able to solve the environment.

Follow-up to #71 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jtpio** [comment]
Linking to a failing build for reference: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=394556&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

**Comment by jtpio** [comment]
Just kicked CI which seems to be green now.

**Comment by jtpio** [comment]
@conda-forge-admin, please rerender

**Comment by jasongrout** [comment]
Nice, thanks!

**Comment by jasongrout** [comment]
Jeremy, do you want to add yourself as a maintainer as well?

**Comment by jtpio** [comment]
Looks like that already the case on `master` and is enough to also be able to merge on other branch like `dev` here.

**Pull request merged**
