### PR TITLE
Delete the noarch

### PR DESCRIPTION
**Pull request by jasongrout**
noarch packages are only supported in conda 4.3 or later, which was released in Dec 2016 - it's too soon to switch to noarch. We'll switch later after more people have a chance to upgrade to conda 4.3 or later.

### CODE REVIEW

**Comment by jasongrout** [comment]
@conda-forge-admin, please rerender

**Comment by jasongrout** [comment]
@conda-forge/core - is there a way to restart the failing ci/circleci build? I forgot to make a PR from my repo (instead used the edit feature in github), so I think these tests are actually uploading to anaconda.org. When I merge, will that circleci python 3.6 build get redone?

**Comment by scopatz** [comment]
You should have permissions to restart if you are a maintainer on this repo

**Comment by jasongrout** [comment]
Perhaps I need to login somehow? The "Restart" button in the upper right of circle/ci for that failing build says that I need write permissions to restart.

**Comment by scopatz** [comment]
Yeah, you also need to login to circle.  I think it can use gh credentials...

**Comment by jasongrout** [comment]
Thanks. I'll try that.

**Comment by jasongrout** [comment]
It worked! Thanks

**Comment by scopatz** [comment]
woohoo!

**Pull request merged**
